[package]
name = "sg"
version = "0.1.0"
authors = ["Ömer Sinan Ağacan <omeragacan@gmail.com>"]
edition = "2018"
description = "DESCRIPTION HERE"

[dependencies]
ansi_term = "0.12"
clap = "2.33"
tree-sitter = "0.16"

[build-dependencies]
cc = "1.0"
rustc_tools_util = "0.2"
