name: CI

on: [push, pull_request]

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
            submodules: 'recursive'

      - name: Get stable toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            components: rustfmt
            override: true

      - name: Build
        run: cargo build --verbose

  formatting:
    name: 'Check formatting'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get Rust stable toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            components: rustfmt
            override: true

      - name: Check formatting
        run: cargo fmt --all -- --check
